import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import axios from 'axios'; import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:3000';
function App(){const [token,setToken]=useState(localStorage.getItem('token')); const [login,setLogin]=useState({identifier:'',password:''}); const [users,setUsers]=useState([]),[products,setProducts]=useState([]),[txs,setTxs]=useState([]),[deposits,setDeposits]=useState([]); const [tab,setTab]=useState('dashboard');
 const headers=()=>({headers:{authorization:`Bearer ${token}`}}); const load=async()=>{const h=headers(); const [u,p,t,d]=await Promise.all([axios.get(`${API}/api/users`,h),axios.get(`${API}/api/products`,h),axios.get(`${API}/api/transactions`,h),axios.get(`${API}/api/deposits`,h)]); setUsers(u.data.data);setProducts(p.data.data);setTxs(t.data.data);setDeposits(d.data.data)}; useEffect(()=>{if(token)load().catch(()=>{})},[token]);
 if(!token)return <div className="login"><div className="card"><h1>PPOB Admin</h1><input placeholder="Username / WhatsApp" value={login.identifier} onChange={e=>setLogin({...login,identifier:e.target.value})}/><input type="password" placeholder="Password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button onClick={async()=>{const r=await axios.post(`${API}/api/users/login`,login);localStorage.setItem('token',r.data.data.token);setToken(r.data.data.token)}}>Masuk</button></div></div>;
 const approve=async(id)=>{await axios.post(`${API}/api/deposits/${id}/approve`,{},headers());load()};
 return <div className="layout"><aside><h2>PPOB</h2>{['dashboard','users','products','transactions','deposits'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}<button onClick={()=>{localStorage.removeItem('token');setToken(null)}}>Logout</button></aside><main><h1>{tab.toUpperCase()}</h1>{tab==='dashboard'&&<div className="grid">{[['User',users.length],['Saldo',`Rp${users.reduce((a,u)=>a+Number(u.balance),0).toLocaleString('id-ID')}`],['Transaksi',txs.length],['Deposit',deposits.length],['Sukses',txs.filter(x=>x.status==='SUCCESS').length],['Pending',txs.filter(x=>x.status==='PROCESS'||x.status==='PENDING').length]].map(([a,b])=><div className="stat" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>}{tab==='users'&&<Table rows={users} cols={['name','whatsapp_number','username','balance','role','status']}/>} {tab==='products'&&<Table rows={products} cols={['code','name','category','selling_price','margin','status']}/>} {tab==='transactions'&&<Table rows={txs} cols={['reference','user_name','product_code','destination','price','status','provider']}/>} {tab==='deposits'&&<table><thead><tr><th>User</th><th>Amount</th><th>Method</th><th>Status</th><th></th></tr></thead><tbody>{deposits.map(d=><tr key={d.id}><td>{d.user_name}</td><td>Rp{Number(d.amount).toLocaleString('id-ID')}</td><td>{d.method}</td><td>{d.status}</td><td>{d.status==='PENDING'&&<button onClick={()=>approve(d.id)}>Approve</button>}</td></tr>)}</tbody></table>}</main></div>}
function Table({rows,cols}){return <table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{typeof r[c]==='number'&&c.includes('price')?`Rp${r[c].toLocaleString('id-ID')}`:String(r[c]??'')}</td>)}</tr>)}</tbody></table>};
createRoot(document.getElementById('root')).render(<App/>);
